// Work types, and the quotes shown when a session or a session window ends.
//
// `by` is filled in only where the attribution is widely documented. Lines with
// an empty `by` are craft maxims in the app's own voice, deliberately left
// unattributed rather than pinned on someone who may never have said them.

const WORK_TYPES = [
	{ value: "", label: "Not set" },
	{ value: "coding", label: "Coding & Web Development" },
	{ value: "seo", label: "SEO & Digital Marketing" },
	{ value: "email", label: "Email Marketing" },
	{ value: "content", label: "Content Writing & Copywriting" },
	{ value: "design", label: "Graphic Design & UI/UX" },
	{ value: "social", label: "Social Media Management" },
	{ value: "data", label: "Data Analysis & Data Science" },
	{ value: "va", label: "Virtual Assistance" },
	{ value: "video", label: "Video Editing & Production" },
	{ value: "ai", label: "AI & Machine Learning" },
];

const WORK_QUOTES = {
	coding: [
		{ text: "Programs must be written for people to read, and only incidentally for machines to execute.", by: "Harold Abelson" },
		{ text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", by: "Martin Fowler" },
		{ text: "Simplicity is prerequisite for reliability.", by: "Edsger W. Dijkstra" },
		{ text: "Premature optimization is the root of all evil.", by: "Donald Knuth" },
		{ text: "Make it work, make it right, make it fast.", by: "Kent Beck" },
		{ text: "Debugging is twice as hard as writing the code in the first place.", by: "Brian Kernighan" },
		{ text: "Talk is cheap. Show me the code.", by: "Linus Torvalds" },
		{ text: "The most damaging phrase in the language is: it's always been done that way.", by: "Grace Hopper" },
		{ text: "Adding manpower to a late software project makes it later.", by: "Fred Brooks" },
		{ text: "Controlling complexity is the essence of computer programming.", by: "Brian Kernighan" },
		{ text: "Testing shows the presence, not the absence of bugs.", by: "Edsger W. Dijkstra" },
		{ text: "Truth can only be found in one place: the code.", by: "Robert C. Martin" },
		{ text: "Programming isn't about what you know; it's about what you can figure out.", by: "Chris Pine" },
		{ text: "Weeks of coding can save you hours of planning.", by: "" },
		{ text: "The bug is never where you are certain it is.", by: "" },
		{ text: "Name the thing well and half the design argument disappears.", by: "" },
		{ text: "Two minutes reading yesterday's diff beats an hour of guessing.", by: "" },
		{ text: "Ship the small change today. The rewrite can wait for a version that has users.", by: "" },
		{ text: "Delete more than you add and the codebase gets easier every week.", by: "" },
		{ text: "The function you can hold in your head is the function you can fix at 2am.", by: "" },
	],

	seo: [
		{ text: "Content is king.", by: "Bill Gates" },
		{ text: "Don't build links. Build relationships.", by: "Rand Fishkin" },
		{ text: "The consumer isn't a moron; she is your wife.", by: "David Ogilvy" },
		{ text: "Marketing is no longer about the stuff you make, but about the stories you tell.", by: "Seth Godin" },
		{ text: "Google only loves you when everyone else loves you first.", by: "Wendy Piersall" },
		{ text: "Half the money I spend on advertising is wasted; the trouble is I don't know which half.", by: "John Wanamaker" },
		{ text: "SEO is not something you do anymore. It's what happens when you do everything else right.", by: "Chad Pollitt" },
		{ text: "Make the customer the hero of your story.", by: "Ann Handley" },
		{ text: "The best marketing doesn't feel like marketing.", by: "Tom Fishburne" },
		{ text: "Either write something worth reading or do something worth writing about.", by: "Benjamin Franklin" },
		{ text: "Rankings are a scoreboard, not a strategy.", by: "" },
		{ text: "Write the page a human would bookmark. The crawler will catch up.", by: "" },
		{ text: "One page that answers the question fully beats ten that circle it.", by: "" },
		{ text: "Keyword research is just listening to how people ask for help.", by: "" },
		{ text: "Traffic without intent is a crowd, not customers.", by: "" },
		{ text: "The fastest SEO win is usually a page you already have.", by: "" },
		{ text: "Fix the title tag today; the backlink campaign can wait.", by: "" },
		{ text: "Search rewards patience more reliably than it rewards cleverness.", by: "" },
		{ text: "If it only exists to rank, it will eventually stop ranking.", by: "" },
		{ text: "Two minutes on one internal link is a better use of today than another audit.", by: "" },
	],

	email: [
		{ text: "Permission marketing is anticipated, personal, and relevant.", by: "Seth Godin" },
		{ text: "People do not buy goods and services. They buy relations, stories and magic.", by: "Seth Godin" },
		{ text: "Good content isn't about good storytelling. It's about telling a true story well.", by: "Ann Handley" },
		{ text: "On the average, five times as many people read the headline as read the body copy.", by: "David Ogilvy" },
		{ text: "The more informative your advertising, the more persuasive it will be.", by: "David Ogilvy" },
		{ text: "Nobody reads ads. People read what interests them. Sometimes it's an ad.", by: "Howard Gossage" },
		{ text: "Every element must first and foremost compel the reading of the first sentence.", by: "Joseph Sugarman" },
		{ text: "You cannot bore people into buying your product.", by: "David Ogilvy" },
		{ text: "Write to one person. The list is a room full of them, one at a time.", by: "" },
		{ text: "The subject line earns the open; the first line earns the rest.", by: "" },
		{ text: "Send the email you'd be glad to receive on a busy Tuesday.", by: "" },
		{ text: "A smaller list that waits for you beats a big one that tolerates you.", by: "" },
		{ text: "Every unsubscribe is feedback that arrived politely.", by: "" },
		{ text: "One clear ask converts better than three good ones.", by: "" },
		{ text: "Segments are just the courtesy of not wasting someone's attention.", by: "" },
		{ text: "If you wouldn't say it out loud, don't schedule it.", by: "" },
		{ text: "Consistency is the whole deliverability strategy most senders never try.", by: "" },
		{ text: "Two minutes rewriting the subject line is the highest-paid work in the campaign.", by: "" },
		{ text: "Write the P.S. first. It is the second most read line you have.", by: "" },
		{ text: "The welcome email is the only one everybody opens. Spend your best words there.", by: "" },
	],

	content: [
		{ text: "Omit needless words.", by: "William Strunk Jr." },
		{ text: "Vigorous writing is concise.", by: "William Strunk Jr." },
		{ text: "Murder your darlings.", by: "Arthur Quiller-Couch" },
		{ text: "Easy reading is damn hard writing.", by: "Nathaniel Hawthorne" },
		{ text: "Hard writing makes easy reading.", by: "Wallace Stegner" },
		{ text: "Copy is not written. Copy is assembled.", by: "Eugene Schwartz" },
		{ text: "People don't buy from clowns.", by: "Claude Hopkins" },
		{ text: "Write the way you talk. Naturally.", by: "David Ogilvy" },
		{ text: "Nobody reads ads. People read what interests them. Sometimes it's an ad.", by: "Howard Gossage" },
		{ text: "The more informative your advertising, the more persuasive it will be.", by: "David Ogilvy" },
		{ text: "Make the customer the hero of your story.", by: "Ann Handley" },
		{ text: "Substitute damn every time you're inclined to write very; your editor will delete it.", by: "Mark Twain" },
		{ text: "The first sentence exists to make the second one read.", by: "" },
		{ text: "Specific beats clever. Always.", by: "" },
		{ text: "Cut the throat-clearing. Your real opening is usually paragraph two.", by: "" },
		{ text: "If you can't say it plainly, you don't understand it yet.", by: "" },
		{ text: "Read it aloud. Your ear finds what your eye forgives.", by: "" },
		{ text: "Write badly on purpose for two minutes; editing has to have something to work on.", by: "" },
		{ text: "One idea per sentence. One promise per page.", by: "" },
		{ text: "The reader owes you nothing. Earn every line.", by: "" },
	],

	design: [
		{ text: "Good design is as little design as possible.", by: "Dieter Rams" },
		{ text: "Less, but better.", by: "Dieter Rams" },
		{ text: "Design is not just what it looks like and feels like. Design is how it works.", by: "Steve Jobs" },
		{ text: "Design is the silent ambassador of your brand.", by: "Paul Rand" },
		{ text: "Don't make me think.", by: "Steve Krug" },
		{ text: "The details are not the details. They make the design.", by: "Charles Eames" },
		{ text: "Design is thinking made visual.", by: "Saul Bass" },
		{ text: "There is no such thing as a boring project. There are only boring solutions.", by: "Massimo Vignelli" },
		{ text: "Content precedes design. Design in the absence of content is not design, it's decoration.", by: "Jeffrey Zeldman" },
		{ text: "If you think good design is expensive, you should look at the cost of bad design.", by: "Ralf Speth" },
		{ text: "A user interface is like a joke. If you have to explain it, it's not that good.", by: "Martin LeBlanc" },
		{ text: "Everything is designed. Few things are designed well.", by: "Brian Reed" },
		{ text: "Whitespace is not empty. It is the reason the rest is readable.", by: "" },
		{ text: "Align it to something. Anything. Just not nothing.", by: "" },
		{ text: "Two typefaces are a system. Five are an argument.", by: "" },
		{ text: "Design the empty state first; that is where most users meet you.", by: "" },
		{ text: "If the user has to zoom, the decision was made for them.", by: "" },
		{ text: "Contrast is accessibility wearing a nicer coat.", by: "" },
		{ text: "Move it two pixels and look again. That is most of the craft.", by: "" },
		{ text: "The mockup that survives contact with real content is the only one that counts.", by: "" },
	],

	social: [
		{ text: "Content is fire, social media is gasoline.", by: "Jay Baer" },
		{ text: "Social media is about sociology and psychology more than technology.", by: "Brian Solis" },
		{ text: "Don't say anything online that you wouldn't want plastered on a billboard with your face on it.", by: "Erin Bury" },
		{ text: "Marketers need to build digital relationships and reputation before closing a sale.", by: "Chris Brogan" },
		{ text: "Jab, jab, jab, right hook.", by: "Gary Vaynerchuk" },
		{ text: "The best marketing doesn't feel like marketing.", by: "Tom Fishburne" },
		{ text: "Marketing is no longer about the stuff you make, but about the stories you tell.", by: "Seth Godin" },
		{ text: "Your brand is what people say about you when you're not in the room.", by: "Jeff Bezos" },
		{ text: "It takes 20 years to build a reputation and five minutes to ruin it.", by: "Warren Buffett" },
		{ text: "Post like someone you respect is reading. Someone is.", by: "" },
		{ text: "Reply to the comment before you write the next post.", by: "" },
		{ text: "Consistency beats virality on every timeline longer than a week.", by: "" },
		{ text: "One community you actually talk to beats five channels you broadcast at.", by: "" },
		{ text: "Schedule the week in one sitting so the day is free to be human.", by: "" },
		{ text: "Vanity metrics feel like progress right up until the invoice.", by: "" },
		{ text: "If the caption needs the algorithm to work, the caption doesn't work.", by: "" },
		{ text: "Two minutes writing one honest sentence beats an hour chasing a trend.", by: "" },
		{ text: "Every platform rents you the audience. The list is the only thing you own.", by: "" },
		{ text: "Show the work, not just the win.", by: "" },
		{ text: "The account that shows up on the quiet days is the one people trust on the loud ones.", by: "" },
	],

	data: [
		{ text: "In God we trust. All others must bring data.", by: "W. Edwards Deming" },
		{ text: "Without data you're just another person with an opinion.", by: "W. Edwards Deming" },
		{ text: "All models are wrong, but some are useful.", by: "George E. P. Box" },
		{ text: "The greatest value of a picture is when it forces us to notice what we never expected to see.", by: "John Tukey" },
		{ text: "Above all else show the data.", by: "Edward Tufte" },
		{ text: "Torture the data, and it will confess to anything.", by: "Ronald Coase" },
		{ text: "Data is not information, information is not knowledge, knowledge is not wisdom.", by: "Clifford Stoll" },
		{ text: "The goal is to turn data into information, and information into insight.", by: "Carly Fiorina" },
		{ text: "Statistics is the grammar of science.", by: "Karl Pearson" },
		{ text: "Errors using inadequate data are much less than those using no data at all.", by: "Charles Babbage" },
		{ text: "The plural of anecdote is not data.", by: "Roger Brinner" },
		{ text: "An approximate answer to the right question is worth far more than a precise answer to the wrong one.", by: "John Tukey" },
		{ text: "Plot it before you model it.", by: "" },
		{ text: "The outlier is a story, not a nuisance. Read it before you drop it.", by: "" },
		{ text: "Half of analysis is cleaning; the other half is admitting what the data can't say.", by: "" },
		{ text: "A confidence interval is an act of honesty.", by: "" },
		{ text: "If the result surprises you, check the join before you check the theory.", by: "" },
		{ text: "Two minutes writing down the question saves a day of aimless querying.", by: "" },
		{ text: "Correlation is an invitation to investigate, not a conclusion to ship.", by: "" },
		{ text: "The dashboard nobody opens is a report you wrote to yourself.", by: "" },
	],

	va: [
		{ text: "Your mind is for having ideas, not holding them.", by: "David Allen" },
		{ text: "Efficiency is doing things right; effectiveness is doing the right things.", by: "Peter Drucker" },
		{ text: "What gets measured gets managed.", by: "Peter Drucker" },
		{ text: "Being busy is a form of laziness — lazy thinking and indiscriminate action.", by: "Tim Ferriss" },
		{ text: "You can have everything in life you want, if you will just help other people get what they want.", by: "Zig Ziglar" },
		{ text: "People will forget what you said, but people will never forget how you made them feel.", by: "Maya Angelou" },
		{ text: "The best way to find yourself is to lose yourself in the service of others.", by: "Mahatma Gandhi" },
		{ text: "Do what you do so well that they will want to see it again and bring their friends.", by: "Walt Disney" },
		{ text: "Never mistake motion for action.", by: "Ernest Hemingway" },
		{ text: "It is not enough to be busy. The question is: what are we busy about?", by: "Henry David Thoreau" },
		{ text: "The inbox is someone else's plan for your day. Open it on purpose.", by: "" },
		{ text: "Confirm in writing. Future you is the client too.", by: "" },
		{ text: "A checklist is a promise you don't have to remember.", by: "" },
		{ text: "Batch the small things; they are only small in isolation.", by: "" },
		{ text: "The task you keep rescheduling is telling you something. Listen to it for two minutes.", by: "" },
		{ text: "Reliable beats fast, every quarter of every year.", by: "" },
		{ text: "Say the deadline out loud before you agree to it.", by: "" },
		{ text: "Document it once and you never explain it twice.", by: "" },
		{ text: "Protect one quiet block a day. That is where the real work fits.", by: "" },
		{ text: "Under-promise in the message, over-deliver in the file.", by: "" },
	],

	video: [
		{ text: "Drama is life with the dull bits cut out.", by: "Alfred Hitchcock" },
		{ text: "Cinema is a matter of what's in the frame and what's out.", by: "Martin Scorsese" },
		{ text: "Film is truth 24 times a second.", by: "Jean-Luc Godard" },
		{ text: "Editing is not so much a putting together as it is a discovery of a path.", by: "Walter Murch" },
		{ text: "If it can be written, or thought, it can be filmed.", by: "Stanley Kubrick" },
		{ text: "A film is never really good unless the camera is an eye in the head of a poet.", by: "Orson Welles" },
		{ text: "Montage is conflict.", by: "Sergei Eisenstein" },
		{ text: "You can't have art without resistance in the materials.", by: "William Morris" },
		{ text: "The most honest form of filmmaking is to make a film for yourself.", by: "Peter Jackson" },
		{ text: "Cut on the movement and the audience never notices the seam.", by: "" },
		{ text: "Sound carries half the story and takes a quarter of the time.", by: "" },
		{ text: "If you're bored watching it, they left two minutes ago.", by: "" },
		{ text: "The rough cut is supposed to be rough. Finish it before you polish it.", by: "" },
		{ text: "Label the bins today so tomorrow's you can actually edit.", by: "" },
		{ text: "One more pass with fresh eyes beats three passes tonight.", by: "" },
		{ text: "Colour last. Story first.", by: "" },
		{ text: "The shot you love is usually the one to cut.", by: "" },
		{ text: "Render early; discover the problem while there's still time.", by: "" },
		{ text: "Two minutes trimming the first ten seconds saves the whole video.", by: "" },
		{ text: "Silence is an edit. Use it.", by: "" },
	],

	ai: [
		{ text: "Can machines think?", by: "Alan Turing" },
		{ text: "Machines take me by surprise with great frequency.", by: "Alan Turing" },
		{ text: "Machine learning gives computers the ability to learn without being explicitly programmed.", by: "Arthur Samuel" },
		{ text: "AI is the new electricity.", by: "Andrew Ng" },
		{ text: "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim.", by: "Edsger W. Dijkstra" },
		{ text: "More data beats clever algorithms, but better data beats more data.", by: "Peter Norvig" },
		{ text: "A breakthrough in machine learning would be worth ten Microsofts.", by: "Bill Gates" },
		{ text: "Prediction is very difficult, especially about the future.", by: "Niels Bohr" },
		{ text: "It is change, continuing change, inevitable change, that is the dominant factor in society today.", by: "Isaac Asimov" },
		{ text: "Our intelligence is what makes us human, and AI is an extension of that quality.", by: "Yann LeCun" },
		{ text: "The baseline you skipped is the result you can't interpret.", by: "" },
		{ text: "If the metric went up and you're not sure why, it went up for the wrong reason.", by: "" },
		{ text: "Look at the data by hand for two minutes. It will outperform an hour of tuning.", by: "" },
		{ text: "A model that can't be explained can still be wrong — just quietly.", by: "" },
		{ text: "Every leak in the validation set is a promotion you'll have to give back.", by: "" },
		{ text: "Start with the dumbest model that could work; you'll need something to beat.", by: "" },
		{ text: "Evaluation is the product. The model is an implementation detail.", by: "" },
		{ text: "Garbage in, confidently formatted garbage out.", by: "" },
		{ text: "The failure cases are the documentation nobody writes.", by: "" },
		{ text: "Ship the small model that runs today over the big one that might.", by: "" },
	],
};

module.exports = { WORK_TYPES, WORK_QUOTES };
